mutation createTask($user_id: Int!, $title: String!, $description: String) {
    createTask(
        input: {
            user_id: $user_id,
            title: $title,
            description: $description
        }
    ) {
        id
        title
        description
        user {
            id
            name
            email
        }
        created_at
        updated_at
    }
}