mutation deleteTask($id: ID!) {
    deleteTask(id: $id) {
        id
        title
        description
        user {
            id
            name
            email
        }
        created_at
        updated_at
    }
}